package sync

import (
	"errors"
	"testing"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/public/plugin/plugintest"
	"github.com/mattermost/mattermost/server/public/pluginapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func TestSyncFields(t *testing.T) {
	groupID := "test-group-id"
	pluginID := "test-plugin-id"

	t.Run("creates all fields and returns ID cache", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName returning not found (fields don't exist yet)
		api.On("GetPropertyFieldByName", groupID, "", "job_title").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "programs").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "clearance").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "start_date").Return(nil, errors.New("not found")).Once()

		// Mock field creation - ID is generated by Mattermost
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "job_title" && f.ID == ""
		})).Return(&model.PropertyField{ID: "generated_id_1", Name: "job_title", Type: model.PropertyFieldTypeText}, nil)

		programsField := &model.PropertyField{
			ID:   "generated_id_2",
			Name: "programs",
			Type: model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "programs" && f.ID == ""
		})).Return(programsField, nil)

		clearanceField := &model.PropertyField{
			ID:   "generated_id_3",
			Name: "clearance",
			Type: model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "clearance" && f.ID == ""
		})).Return(clearanceField, nil)

		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "start_date" && f.ID == ""
		})).Return(&model.PropertyField{ID: "generated_id_4", Name: "start_date", Type: model.PropertyFieldTypeDate}, nil)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, "generated_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "generated_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "generated_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "generated_id_4", cache.GetFieldID("start_date"))
		assert.Equal(t, "opt_id_1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt_id_2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt_id_3", cache.GetOptionID("programs", "Lemons"))
		assert.Equal(t, "opt_id_4", cache.GetOptionID("clearance", "CUI"))
		assert.Equal(t, "opt_id_5", cache.GetOptionID("clearance", "Confidential"))
		assert.Equal(t, "opt_id_6", cache.GetOptionID("clearance", "Secret"))
		assert.Equal(t, "opt_id_7", cache.GetOptionID("clearance", "Top Secret"))
		api.AssertExpectations(t)
	})

	t.Run("updates existing fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName for each field (simulating they exist)
		existingJobTitle := &model.PropertyField{
			ID:      "existing_id_1",
			GroupID: groupID,
			Name:    "job_title",
			Type:    model.PropertyFieldTypeText,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "job_title").Return(existingJobTitle, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_1"
		})).Return(existingJobTitle, nil).Once()

		existingPrograms := &model.PropertyField{
			ID:      "existing_id_2",
			GroupID: groupID,
			Name:    "programs",
			Type:    model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "programs").Return(existingPrograms, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_2"
		})).Return(existingPrograms, nil).Once()

		existingClearance := &model.PropertyField{
			ID:      "existing_id_3",
			GroupID: groupID,
			Name:    "clearance",
			Type:    model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "clearance").Return(existingClearance, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_3"
		})).Return(existingClearance, nil).Once()

		existingStartDate := &model.PropertyField{
			ID:      "existing_id_4",
			GroupID: groupID,
			Name:    "start_date",
			Type:    model.PropertyFieldTypeDate,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "start_date").Return(existingStartDate, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_4"
		})).Return(existingStartDate, nil).Once()

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, "existing_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "existing_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "existing_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "existing_id_4", cache.GetFieldID("start_date"))
		api.AssertExpectations(t)
	})

	t.Run("multiselect & rank fields include options", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName returning not found for all fields
		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))

		// Mock field creation - verify Programs field has options
		multiSelectOptionsVerified := false
		rankOptionsVerified := false
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			if f.Name == "programs" {
				// Verify Programs field has correct options (Apples, Oranges, Lemons, Grapes)
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})
				if ok && len(options) == 4 {
					multiSelectOptionsVerified = true
				}
			}
			if f.Name == "clearance" {
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})

				if ok && len(options) == 4 {
					// Check for Rank as well
					numRanks := 0
					for _, option := range options {
						opt, ok := option.(map[string]interface{})
						if !ok {
							break
						}
						_, ok = opt["rank"]
						if ok {
							numRanks++
						}
					}
					if numRanks == 4 {
						rankOptionsVerified = true
					}
				}
			}
			return true
		})).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			// Return field with generated ID
			f.ID = "gen_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
					map[string]interface{}{"id": "opt2", "name": "Oranges"},
					map[string]interface{}{"id": "opt3", "name": "Lemons"},
					map[string]interface{}{"id": "opt4", "name": "Grapes"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt6", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt7", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt8", "name": "Top Secret", "rank": 4},
				}
			}
			return f, nil
		})

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID)

		require.NoError(t, err)
		assert.True(t, multiSelectOptionsVerified, "Options should be verified during field creation")
		assert.True(t, rankOptionsVerified, "Ranks should be present on all rank field options")
		assert.NotNil(t, cache)
	})

	t.Run("continues on partial failures", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName - all fields don't exist
		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))

		createCallCount := 0
		// First field creation fails, others succeed
		api.On("CreatePropertyField", mock.Anything).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			createCallCount++
			if createCallCount == 1 {
				// First call fails
				return nil, errors.New("API error")
			}
			// Subsequent calls succeed
			f.ID = "generated_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
				}
			}
			return f, nil
		})

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID)

		// Should not return error (graceful degradation)
		require.NoError(t, err)
		require.NotNil(t, cache)
	})
}

func TestFieldIDCache(t *testing.T) {
	t.Run("GetFieldID returns correct field IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: map[string]string{
				"job_title":  "id1",
				"programs":   "id2",
				"clearance":  "id3",
				"start_date": "id4",
			},
		}
		assert.Equal(t, "id1", cache.GetFieldID("job_title"))
		assert.Equal(t, "id2", cache.GetFieldID("programs"))
		assert.Equal(t, "id3", cache.GetFieldID("clearance"))
		assert.Equal(t, "id4", cache.GetFieldID("start_date"))
	})

	t.Run("GetFieldID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetFieldID("unknown_field"))
	})

	t.Run("GetOptionID returns correct option IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: map[string]string{
				"programs|Apples":  "opt1",
				"programs|Oranges": "opt2",
				"programs|Lemons":  "opt3",
			},
		}
		assert.Equal(t, "opt1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt3", cache.GetOptionID("programs", "Lemons"))
	})

	t.Run("GetOptionID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("unknown", "Apples"))
	})

	t.Run("GetOptionID returns empty string for unknown option", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("programs", "Unknown"))
	})
}
